### PR TITLE
Resolves issue #3

### LINKED ISSUE #3: LIC 0
Launch Interceptor Conditions (LIC) are defined as follows:
LIC0. There exists at least one set of two consecutive data points that are a distance greater than the length, LENGTH1, apart.
(0 ≤ LENGTH1)

Consecutive: Two points are consecutive if they are adjacent in the input data vectors X and Y. Thus (X[i],Y[i]) and (X[i+1],Y[i+1]) are adjacent.

### PR DESCRIPTION
**Pull request by benronkth**
Compeletes LIC0 and LIC0Test

### CODE REVIEW

**Review by Eyskha — APPROVED** [review]
Ok for me.
You could have added a test case with more than 2 data points and where no set of 2 consecutive points are more than LENGTH_1 away but some non-consecutive points might be. This would be to verify the influence of consecutiveness.

PS: You have forgotten to link the issue in the pull request message so the pull request doesn't appear as solving the issue both in the project table and in the issue. Writting in the title of the request doesn't seem to be enough.

**Review by nickyobreykov — APPROVED** [review]
LGTM.
I believe we can assume that NUMPOINTS >= 2 as stated in "2. Required Computations"? Thus testing for the points array being empty or having one element is not necessary.

**Comment by benronkth** [comment]
@nickyobreykov Your comment is true and the constraints apply, I  wanted to have some edge cases and thus added these. Should I remove these test cases and create new edge cases?

**Comment by benronkth** [comment]
@Eyskha Applied your suggestion and there is now a dedicated test for non-consecutive points.

**Review by leddy231 — APPROVED** [review]

**Pull request merged**
